# APPLICATION CONFIG
spring.application.name=AUREUS
server.port=8080

# DATABASE CONFIG
spring.datasource.url=jdbc:mysql://localhost:3306/crypto_trading_platform?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT CONFIG
jwt.secret=YOUR_JWT_SECRET
jwt.expiration=86400000